config/routes.rb
Rails.application.routes.draw do
  resources :plans do
    member do
      put :generate
      put :reset
      get :send_email
      post :send_email
    end
  end

  resources :resources

  root to: 'plans#index'

end

app/models/assigment.rb
class Assigment < ActiveRecord::Base
  belongs_to :resource
  belongs_to :plan

  delegate :date, to: :shift

  validates :plan_id, :resource_id, presence: true

  def shift_at(day_offset)
    Shift.find(pattern[day_offset]) if pattern && pattern[day_offset]
  end

  def shift_at_set(day_offset, value)
    pattern[day_offset] = Shift.find(value).to_s
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  WEEKS_COUNT = 5

  validates :start_date, :title, presence: true
  validate :start_date_must_start_at_monday
  validate :start_date_must_be_unchanged, on: :update

  has_many :assigments

  before_validation :generate_title_if_empty!

  def weeks_count
    (dates.count / 7.0).ceil
  end

  def send_email?
    assigments.any?
  end

  def reset!
    assigments.destroy_all
  end

  def reset?
    assigments.any?
  end

  def generate!(resources = Resource.all)
    reset!
    PlanGenerator.new(self, resources).generate!
  end

  def generate?
    true
  end

  def dates
    (start_date..end_date)
  end

  def end_date
    start_date + WEEKS_COUNT.weeks - 1.day if start_date
  end

  def shift_for_resources_at(resource, date)
    return nil unless assigment = assigments.find { |assigment| assigment.resource == resource }
    Shift.find(assigment.pattern[date - start_date])
  end

  private

  def generate_title_if_empty!
    self.title = "#{start_date} - #{end_date}" if title.blank?
  end

  def start_date_must_start_at_monday
    errors.add(:start_date, 'must start at Monday') unless start_date.monday?
  end

  def end_date_must_be_unchanged
    errors.add(:start_date, 'read only value') if start_date_changed?
  end

end

app/models/plan_email.rb
class PlanEmail
  include ActiveModel::Model

  attr_accessor :email, :plan

  validates :email, :plan, presence: true

  def send_email
    valid? && mailer.plan(plan, email).deliver
  end

  private

  def mailer
    PlanMailer
  end
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  validates :first_name, :last_name, :hours_per_week, presence: true
  validates :hours_per_week, numericality: true

  has_many :assigments

  serialize :allowed_shifts_type, Array

  before_save :make_allowed_shifts_type_uniq!

  def same_profile?(resource)
    resource.is_a?(self.class) && resource.profile_hash == profile_hash
  end

  def max_shifts(weeks: 1)
    ((4+hours_per_week*weeks)/8.0).floor
  end

  def full_name
    [*first_name, *last_name].join(' ')
  end

  def profile_hash
    [*allowed_shifts_type, hours_per_week].hash
  end

  def allowed_shifts_types_short
    allowed_shifts_type.map{ |type| type[0] }.join.upcase
  end

  def allowed_nights?
    allowed_shifts_type.any? { |type| type == Shift::NIGHT }
  end

  def allowed_anydays?
    allowed_shifts_type.any? { |type| Shift::DAY_TYPES.include? type }
  end

  private

  def make_allowed_shifts_type_uniq!
    allowed_shifts_type.uniq!
    allowed_shifts_type.reject(&:blank?)
  end
end

app/models/shift.rb
class Shift
  DAY    = 'day'.freeze
  EARLY  = 'early'.freeze
  LATE   = 'late'.freeze
  NIGHT  = 'night'.freeze
  ANYDAY = 'anyday'.freeze
  REST   = 'rest'.freeze

  REAL_TYPES    = [DAY, EARLY, LATE, NIGHT].freeze
  VIRTUAL_TYPES = [ANYDAY, REST].freeze
  DAY_TYPES     = [DAY, EARLY, LATE, ANYDAY].freeze
  TYPES         = (REAL_TYPES + VIRTUAL_TYPES).freeze

  attr_reader :type

  def initialize(type)
    @type = TYPES.find { |t| t && self.class.send(:key, t) == self.class.send(:key, type) }
    # raise "unknown shift type #{type.inspect}" unless @type
  end

  class << self
    def find(type)
      all[key(type)] ||= new(type).freeze
    end

    private

    def key(type)
      type.to_s.downcase[0]
    end

    def all
      @all ||= {}
    end
  end

  TYPES.each do |type|
    define_method :"#{type}?" do
      self.type == type
    end
  end

  def free?
    rest?
  end

  def work?
    day? || early? || late? || night? || anyday?
  end

  def eql?(shift)
    type == shift.type
  end

  def to_s
    type.to_s.upcase[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy, :generate, :reset, :send_email]

  respond_to :html

  def index
    @plans = Plan.all
    respond_with(@plans)
  end

  def show
    @resources = Resource.all
    respond_with(@plan)
  end

  def new
    @plan = Plan.new(start_date: date_at_next_week_monday)
    respond_with(@plan)
  end

  def edit
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.save
    respond_with(@plan)
  end

  def generate
    @plan.generate!
    respond_with @plan, location: plan_url(@plan)
  end

  def reset
    @plan.reset!
    respond_with @plan, location: plan_url(@plan)
  end

  def update
    @plan.update(plan_params)
    respond_with(@plan)
  end

  def destroy
    @plan.destroy
    respond_with(@plan)
  end

  def send_email
    @plan_email = PlanEmail.new plan_email_params
    @message = !request.get? && @plan_email.send_email
    if @message
      respond_with @plan_email, notice: "Email has been sent.", status: :created
    end
  end

  private

  def date_at_next_week_monday
    Date.today.at_beginning_of_week+7.days
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_email_params
    !request.get? ? params.require(:plan_email).permit(:email).merge(plan: @plan) : {}
  end

  def plan_params
    params.require(:plan).permit(:start_date, :title)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @resources = Resource.all
    respond_with(@resources)
  end

  def show
    respond_with(@resource)
  end

  def new
    @resource = Resource.new
    respond_with(@resource)
  end

  def edit
  end

  def create
    @resource = Resource.new(resource_params)
    @resource.save
    respond_with(@resource)
  end

  def update
    @resource.update(resource_params)
    respond_with(@resource)
  end

  def destroy
    @resource.destroy
    respond_with(@resource)
  end

  private
    def set_resource
      @resource = Resource.find(params[:id])
    end

    def resource_params
      params.require(:resource).permit(:first_name, :last_name, :hours_per_week, allowed_shifts_type: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |msg_type, message|
  = content_tag :div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in" do
    = content_tag :button, 'x', class: "close", data: { dismiss: 'alert' }
    = concat message

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      =link_to 'H+', root_url, class: 'navbar-brand'
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to 'plans', Plan
        %li= link_to 'resources', Resource

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Harmonogram
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    = render 'layouts/flash'

    .container-fluid
      = yield

app/views/plans/_email_form.html.haml
- if @message
  %h3 message has been sent
= simple_form_for @plan_email, url: send_email_plan_url(@plan) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email

  .form-actions
    = f.button :submit, value: "Send email", class: 'btn btn-default'

app/views/plans/_form.html.haml
= simple_form_for(@plan) do |f|
  = f.error_notification

  .form-inputs
    = f.input :start_date
    = f.input :title

  .form-actions
    = f.button :submit

app/views/plans/_plan.html.haml
%table.table.plan.table-fluid
  %thead
    %tr
      %th

      - @plan.dates.each do |date|
        %th{title:date, class: [*(date.saturday? || date.sunday? ? :weekend : nil)] }
          =date.day
  %tbody
    - @resources.each do |resource|
      %tr
        %th
          = link_to "#{resource.full_name} [#{resource.hours_per_week}] [#{resource.allowed_shifts_types_short}]", resource
        - @plan.dates.each do |date|
          %td{class: [*(date.saturday? || date.sunday? ? :weekend : nil), @plan.shift_for_resources_at(resource, date).try(:type)]}
            = @plan.shift_for_resources_at(resource, date)

app/views/plans/edit.html.haml
%h1 Editing plan

= render 'form'

.actions
  = link_to 'Show', @plan, class: 'btn btn-default'
  = link_to 'Back', plans_path, class: 'btn btn-default'

app/views/plans/index.html.haml
%h1 Listing plans

%table.table
  %thead
    %tr
      %th Start date
      %th End date
      %th Title
      %th

  %tbody
    - @plans.each do |plan|
      %tr
        %td= plan.start_date
        %td= plan.end_date
        %td= plan.title
        %td
          = link_to 'Show', plan, class: 'btn btn-default'
          = link_to 'Edit', edit_plan_path(plan), class: 'btn btn-default'
          = link_to 'Destroy', plan, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

.actions
  = link_to 'New Plan', new_plan_path, class: 'btn btn-default'

app/views/plans/new.html.haml
%h1 New plan

= render 'form'

.actions
  = link_to 'Back', plans_path, class: 'btn btn-default'

app/views/plans/send_email.html.haml
%h1 Send plan

= render 'email_form'

.actions
  = link_to 'Back', @plan, class: 'btn btn-default'

app/views/plans/show.html.haml
%p#notice= notice

%p
  %b Start date:
  = @plan.start_date
%p
  %b End date:
  = @plan.end_date
%p
  %b Title:
  = @plan.title

= render @plan

.actions
  = link_to 'Edit', edit_plan_path(@plan), class: 'btn btn-default'
  = link_to 'Reset', reset_plan_path(@plan), method: :put, class: 'btn btn-default' if @plan.reset?
  = link_to 'Email', send_email_plan_path(@plan), class: 'btn btn-default' if @plan.send_email?
  = link_to 'Generate', generate_plan_path(@plan), method: :put, class: 'btn btn-default' if @plan.generate?
  = link_to 'Back', plans_path, class: 'btn btn-default'

app/views/resources/_form.html.haml
= simple_form_for @resource do |f|
  = f.error_notification
  .form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :hours_per_week
    = f.input :allowed_shifts_type, as: :check_boxes, collection: Shift::TYPES

  .form-actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/resources/edit.html.haml
%h1 Editing resource

= render 'form'

.actions
  = link_to 'Show', @resource, class: 'btn btn-default'
  = link_to 'Back', resources_path, class: 'btn btn-default'

app/views/resources/index.html.haml
%h1 Listing resources

%table.table
  %thead
    %tr
      %th First name
      %th Last name
      %th Hours/week
      %th Allowed shifts type
      %th
      %th
      %th

  %tbody
    - @resources.each do |resource|
      %tr
        %td= resource.first_name
        %td= resource.last_name
        %td= resource.hours_per_week
        %td= resource.allowed_shifts_type.join(', ')
        %td
          = link_to 'Show', resource, class: 'btn btn-default'
          = link_to 'Edit', edit_resource_path(resource), class: 'btn btn-default'
          = link_to 'Destroy', resource, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

.actions
  = link_to 'New Resource', new_resource_path, class: 'btn btn-default'

app/views/resources/new.html.haml
%h1 New resource

= render 'form'
.actions
  = link_to 'Back', resources_path, class: 'btn btn-default'

app/views/resources/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @resource.first_name
%p
  %b Last name:
  = @resource.last_name
%p
  %b Hours per week:
  = @resource.hours_per_week
%p
  %b Allowed shifts type:
  = @resource.allowed_shifts_type.join(', ')
.actions
  = link_to 'Edit', edit_resource_path(@resource), class: 'btn btn-default'
  = link_to 'Back', resources_path, class: 'btn btn-default'